### ISSUE TITLE
1.0.0-rc.1 fails to compile.

### ISSUE THREAD

**Issue by t-p-l-k** [basvandenberg/ng-select#252]
After upgrading package version to 1.0.0-rc.1 project build started to fail. Locking version to 1.0.0-beta.6 fixes the issue.
```Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Metadata version mismatch for module /root/node_modules/ng-select/dist/src/option.interface.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/root/node_modules/@angular/compiler/@angular/compiler.es5.js:25556:7)
    at StaticSymbolResolver._createSymbolsOf (/root/node_modules/@angular/compiler/@angular/compiler.es5.js:25344:10)
    at StaticSymbolResolver.getSymbolsOf (/root/node_modules/@angular/compiler/@angular/compiler.es5.js:25325:12)
    at /root/node_modules/@angular/compiler/bundles/compiler.umd.js:24214:30
    at Array.forEach (native)
    at extractProgramSymbols (/root/node_modules/@angular/compiler/@angular/compiler.es5.js:24183:55)
    at AotCompiler.analyzeModulesAsync (/root/node_modules/@angular/compiler/@angular/compiler.es5.js:23741:7)
    at CodeGenerator.codegen (/root/packages/compiler-cli/src/codegen.ts:41:10)
    at /root/node_modules/src/main.ts:19:84
    at Object.main (/tools/@angular/tsc-wrapped/src/main.ts:136:12)
    at Object.runInternal (/root/node_modules/src/main.ts:24:10)
    at /root/node_modules/src/plugin.ts:64:21
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3```

**Comment by Tolitech** [comment]
Same issue.

**Comment by basvandenberg** [comment]
What do you use as build tool? I didn't have any issues with the demo website, or when testing it on a clean angular-cli project.

I just published rc.2, which hopefully fixes this problem. Could you please give it a try and let me know if this works. Thanks for reporting!

**Comment by Wandang** [comment]
Had the same issue with angular CLI. Will test rc2 later. Thx for the fast update!

**Comment by agil-NUBBA** [comment]
Keeps failing, here you have a full `$ng --version`

```
Angular CLI: 1.5.0
Node: 6.11.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... tsc-wrapped, upgrade

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.32
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.35
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.0
typescript: 2.6.1
webpack: 3.8.1
```

**Comment by basvandenberg** [comment]
With what error message does it fail?

**Comment by t-p-l-k** [comment]
@basvandenberg tried 1.0.0-rc.2, same error:
```> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Metadata version mismatch for module C:/users/dmitriy.te/Documents/CurrentProjects/office-troop/tenant-app/node_modules/ng-select/dist/src/option.interface.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\@angular\compiler.es5.js:25556:7)
    at StaticSymbolResolver._createSymbolsOf (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\@angular\compiler.es5.js:25344:10)
    at StaticSymbolResolver.getSymbolsOf (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\@angular\compiler.es5.js:25325:12)
    at C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\bundles\compiler.umd.js:24214:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\@angular\compiler.es5.js:24183:55)
    at AotCompiler.analyzeModulesAsync (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\@angular\compiler\@angular\compiler.es5.js:23741:7)
    at CodeGenerator.codegen (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\packages\compiler-cli\src\codegen.ts:41:10)
    at C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\src\main.ts:19:84
    at Object.main (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tools\@angular\tsc-wrapped\src\main.ts:136:12)
    at Object.runInternal (C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\src\main.ts:24:10)
    at C:\users\dmitriy.te\Documents\CurrentProjects\office-troop\tenant-app\node_modules\src\plugin.ts:64:21
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3```

I'm using heavily modified angular/webpack starter.
All angular packages are 4.3.0
rxjs 5.4.3
webpack 3.5.5
awesome-typescript-loader 3.2.3

**Comment by t-p-l-k** [comment]
Thanks for your quick response btw!

**Comment by theodorejb** [comment]
I'm getting the following error from Webpack 3.8.1 when I try to bundle ng-select with my Angular 5 app:

```
    ERROR in ./compiled_ts/node_modules/ng-select/dist/src/select.component.ngfactory.js
    Module not found: Error: Can't resolve './select-dropdown.component' in 'C:\Users\username\Documents\Code\MyApp\compiled_ts\node_modules\ng-select\dist\src'
     @ ./compiled_ts/node_modules/ng-select/dist/src/select.component.ngfactory.js 10:0-50
     @ ./compiled_ts/src/components/app/app.ngfactory.js
     @ ./compiled_ts/src/app.module.ngfactory.js
     @ ./compiled_ts/src/main.js

    ERROR in ./compiled_ts/node_modules/ng-select/dist/src/select-dropdown.component.ngfactory.js
    Module not found: Error: Can't resolve './select-dropdown.component' in 'C:\Users\username\Documents\Code\MyApp\compiled_ts\node_modules\ng-select\dist\src'
     @ ./compiled_ts/node_modules/ng-select/dist/src/select-dropdown.component.ngfactory.js 9:0-50
     @ ./compiled_ts/node_modules/ng-select/dist/src/select.component.ngfactory.js
     @ ./compiled_ts/src/components/app/app.ngfactory.js
     @ ./compiled_ts/src/app.module.ngfactory.js
     @ ./compiled_ts/src/main.js

    ERROR in ./compiled_ts/node_modules/ng-select/dist/src/select.component.ngfactory.js
    Module not found: Error: Can't resolve './select.component' in 'C:\Users\username\Documents\Code\MyApp\compiled_ts\node_modules\ng-select\dist\src'
     @ ./compiled_ts/node_modules/ng-select/dist/src/select.component.ngfactory.js 12:0-41
     @ ./compiled_ts/src/components/app/app.ngfactory.js
     @ ./compiled_ts/src/app.module.ngfactory.js
     @ ./compiled_ts/src/main.js
```

compiled_ts is the `outDir` set in my tsconfig.json file.

**Comment by basvandenberg** [comment]
Packaging a module is not that straightforward, unfortunately, and apparently changes a lot. Also I'm no expert on this subject, I can't figure out how to fix this issue.

I am considering starting to use ng-packagr for building the module package, which will hopefully save me a lot of headaches...

**Comment by rbarkhouse** [comment]
Having this same issue in a non-cli, webpack 3.4.1 environment.
Related link?  https://github.com/angular/angular/issues/19607

**Comment by cfremgen** [comment]
Same issue in Non-CLI, System JS project.

**Comment by mrsweaters** [comment]
1.0.0-rc.2 works fine with CLI 1.5, Angular 5, and AOT.

**Comment by basvandenberg** [comment]
I updated the build process, now using ng-packagr with angular-cli instead of my own homebrew gulp build-file. Not all to happy about the big change, but it is probably better for the future anyways. 

I hope this solves the issue (and does not lead to other new issues...). I leave the ticket open for now, please let me know if it works. Let's see what happens :).

**Comment by usego** [comment]
How to fight with

localhost/:24 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/traceur
	Error: XHR error (404 Not Found) loading http://localhost:3000/traceur 

?

**Comment by theodorejb** [comment]
@basvandenberg 1.0.0-rc.3 is working for me now. Thanks!

**Comment by t-p-l-k** [comment]
1.0.0-rc.3 works for me too, thanks!
I think it'll be correct to close this issue since this exact problem is resolved.

**Comment by basvandenberg** [comment]
Great! I am happy to hear that. Thanks for reporting the issue.
